spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
          name: spring5-recipe
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
