apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
    app: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
  #clusterIP: None
  selector:
    name: mongo-pod
    app: mongodb
---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    name: mongo-pod
    app: mongodb
spec:
  containers:     #Can be List/Array
    - name: mongo-container
      image: mongo
