apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    name: rabbitmq-service
    app: rabbitmq
spec:
  type: NodePort
  ports:
#  - name: epmd
#    port: 4369
#    targetPort: 4369
  - name: amqp1
    port: 5671
    targetPort: 5671
    nodePort: 30071
  - name: amqp2
    port: 5672
    targetPort: 5672
    nodePort: 30072
#  - name: dist
#    port: 25672
#    targetPort: 25672
#  - name: management1
#    port: 15671
#    targetPort: 15671
  - name: management
    port: 15672
    targetPort: 15672
    nodePort: 30080
  selector:
    name: rabbitmq-pod
    app: rabbitmq
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  labels:
    name: rabbitmq-pod
    app: rabbitmq
spec:
  containers:     #Can be List/Array
    - name: rabbitmq-container
      image: rabbitmq:management
